CREATE TABLE DEPARTAMENTO 
(NUMDEPTO integer PRIMARY KEY NOT NULL AUTO_INCREMENT,
NOMDEPTO VARCHAR(100), 
UBICACIONDPTO VARCHAR(100));

CREATE TABLE EMPLEADO 
(NUMEMPLEADO integer PRIMARY KEY AUTO_INCREMENT,
 NOMBRE VARCHAR(100),
 NUMDEPTO INTEGER,
FOREIGN KEY (NUMDEPTO) REFERENCES DEPARTAMENTO (NUMDEPTO));

INSERT INTO DEPARTAMENTO VALUES(NULL,'INFORMATICA','CHILE');
INSERT INTO DEPARTAMENTO VALUES(NULL,'REDES','CHILE');
INSERT INTO DEPARTAMENTO VALUES(NULL,'PARTES','CHILE');
INSERT INTO DEPARTAMENTO VALUES(NULL,'SALUD','CHILE');
INSERT INTO DEPARTAMENTO VALUES(NULL,'BIENESTAR','CHILE');
INSERT INTO DEPARTAMENTO VALUES(NULL,'ASEO Y ORNATO','CHILE');
INSERT INTO DEPARTAMENTO VALUES(NULL,'CONTABILIDAD','PERU');
INSERT INTO DEPARTAMENTO VALUES(NULL,'RRHH','COLOMBIA');
INSERT INTO DEPARTAMENTO VALUES(NULL,'ASEO Y ORNATO','ARGENTINA');
INSERT INTO DEPARTAMENTO VALUES(NULL,'CONTABILIDAD','BOLIVIA');
INSERT INTO DEPARTAMENTO VALUES(NULL,'RRHH','MEXICO');
INSERT INTO DEPARTAMENTO VALUES(NULL,'CARRETE','CHILE');
INSERT INTO DEPARTAMENTO VALUES(NULL,'SEGURIDAD','PERU');
INSERT INTO DEPARTAMENTO VALUES(NULL,'MARKETING','COLOMBIA');
INSERT INTO DEPARTAMENTO VALUES(NULL,'MECANICA','CHILE');

INSERT INTO EMPLEADO VALUES (NULL,'Matias Zarate', 15);
INSERT INTO EMPLEADO VALUES (NULL,'Felipe Perez', 15);
INSERT INTO EMPLEADO VALUES (NULL,'Bob Marley', 15);
INSERT INTO EMPLEADO VALUES (NULL,'Pedro Polanco', 15);
INSERT INTO EMPLEADO VALUES (NULL,'Eduardo Azul', 15);
INSERT INTO EMPLEADO VALUES (NULL,'Oscar Fernandez', 14);
INSERT INTO EMPLEADO VALUES (NULL,'Maria Jose Velasquez', 14);
INSERT INTO EMPLEADO VALUES (NULL,'Fernanda Parra', 14);
INSERT INTO EMPLEADO VALUES (NULL,'Teresa Valdez', 14);
INSERT INTO EMPLEADO VALUES (NULL,'Ignacio MacGreg', 14);
INSERT INTO EMPLEADO VALUES (NULL,'Rodrigo Zarabia', 13);
INSERT INTO EMPLEADO VALUES (NULL,'Marcelo Zapata', 13);
INSERT INTO EMPLEADO VALUES (NULL,'Mark Jeres', 13);
INSERT INTO EMPLEADO VALUES (NULL,'Cristian Aguirre', 13);
INSERT INTO EMPLEADO VALUES (NULL,'Julian Martel', 13);
INSERT INTO EMPLEADO VALUES (NULL,'Kilos Demetrio', 12);
INSERT INTO EMPLEADO VALUES (NULL,'Astorga Daniel', 12);
INSERT INTO EMPLEADO VALUES (NULL,'Yeny Marlen', 12);
INSERT INTO EMPLEADO VALUES (NULL,'Julia Zapata', 12);
INSERT INTO EMPLEADO VALUES (NULL,'Esteban Cerrado', 12);
INSERT INTO EMPLEADO VALUES (NULL,'Kilos Demetrio Azul', 11);
INSERT INTO EMPLEADO VALUES (NULL,'Pablo Carmona', 11);
INSERT INTO EMPLEADO VALUES (NULL,'Ramon Vicencio', 11);
INSERT INTO EMPLEADO VALUES (NULL,'Julia Veracruz', 11);
INSERT INTO EMPLEADO VALUES (NULL,'Joaquin Mendez', 11);
INSERT INTO EMPLEADO VALUES (NULL,'Ricardo Abrilar', 10);
INSERT INTO EMPLEADO VALUES (NULL,'Rocio Vicencio', 10);
INSERT INTO EMPLEADO VALUES (NULL,'Bianca Vicencio', 10);
INSERT INTO EMPLEADO VALUES (NULL,'Graciela LLancavil', 10);
INSERT INTO EMPLEADO VALUES (NULL,'Enrique Carmona', 10);
INSERT INTO EMPLEADO VALUES (NULL,'Nora Allen', 9);
INSERT INTO EMPLEADO VALUES (NULL,'Ramon Cisco', 9);
INSERT INTO EMPLEADO VALUES (NULL,'Frank Martin', 9);
INSERT INTO EMPLEADO VALUES (NULL,'Milena Snow', 9);
INSERT INTO EMPLEADO VALUES (NULL,'Ruth Vitis', 9);
INSERT INTO EMPLEADO VALUES (NULL,'Sol Marisol', 8);
INSERT INTO EMPLEADO VALUES (NULL,'Jorge Carmona', 8);
INSERT INTO EMPLEADO VALUES (NULL,'Miguel Mac', 8);
INSERT INTO EMPLEADO VALUES (NULL,'Rafael Alarcon', 8);
INSERT INTO EMPLEADO VALUES (NULL,'Ruth Vitis', 8);
INSERT INTO EMPLEADO VALUES (NULL,'Jhon Nieve', 7);
INSERT INTO EMPLEADO VALUES (NULL,'Martin Escoses', 7);
INSERT INTO EMPLEADO VALUES (NULL,'Alex Citrico', 7);
INSERT INTO EMPLEADO VALUES (NULL,'Marcelo de Cachureos', 7);
INSERT INTO EMPLEADO VALUES (NULL,'Alfonso Mastil', 7);
INSERT INTO EMPLEADO VALUES (NULL,'Juan Quiñones', 6);
INSERT INTO EMPLEADO VALUES (NULL,'Adamiro Rojas', 6);
INSERT INTO EMPLEADO VALUES (NULL,'Fernando Maciel', 6);
INSERT INTO EMPLEADO VALUES (NULL,'Carolina Merlot', 6);
INSERT INTO EMPLEADO VALUES (NULL,'Casandra Parra', 6);
INSERT INTO EMPLEADO VALUES (NULL,'Salomon Clavel', 5);
INSERT INTO EMPLEADO VALUES (NULL,'Quiste Martes', 5);
INSERT INTO EMPLEADO VALUES (NULL,'Carlos Zaul', 5);
INSERT INTO EMPLEADO VALUES (NULL,'Eduardo Bomvalet', 5);
INSERT INTO EMPLEADO VALUES (NULL,'Arturo Prat', 5);
INSERT INTO EMPLEADO VALUES (NULL,'Maria Jose Pinganilla', 4);
INSERT INTO EMPLEADO VALUES (NULL,'Carlonia Marsobia', 4);
INSERT INTO EMPLEADO VALUES (NULL,'Jose Jose', 4);
INSERT INTO EMPLEADO VALUES (NULL,'Esternon Peres', 4);
INSERT INTO EMPLEADO VALUES (NULL,'Ivon Cadiz', 4);
INSERT INTO EMPLEADO VALUES (NULL,'Moscard Trek', 3);
INSERT INTO EMPLEADO VALUES (NULL,'Hugo Luis Merc', 3);
INSERT INTO EMPLEADO VALUES (NULL,'Casimiro Lavaca', 3);
INSERT INTO EMPLEADO VALUES (NULL,'Aston Gonzalez', 3);
INSERT INTO EMPLEADO VALUES (NULL,'Crecencio Fretere', 3);
INSERT INTO EMPLEADO VALUES (NULL,'Juan Pedro Pazola', 2);
INSERT INTO EMPLEADO VALUES (NULL,'Roquefort Martin', 2);
INSERT INTO EMPLEADO VALUES (NULL,'Carlos Espertes', 2);
INSERT INTO EMPLEADO VALUES (NULL,'Jino Janos', 2);
INSERT INTO EMPLEADO VALUES (NULL,'Ether Certero', 2);
INSERT INTO EMPLEADO VALUES (NULL,'Pepe Grillo', 1);
INSERT INTO EMPLEADO VALUES (NULL,'Marisol Luna', 1);
INSERT INTO EMPLEADO VALUES (NULL,'Pedro Cortisona', 1);
INSERT INTO EMPLEADO VALUES (NULL,'Eugenio Mundial', 1);
INSERT INTO EMPLEADO VALUES (NULL,'Nelson Gertred', 1);
/*SET GLOBAL time_zone = '-3:00';*/

